# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 70, 481, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Nhanh = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Nhanh.setObjectName("pushButton_Nhanh")
        self.gridLayout.addWidget(self.pushButton_Nhanh, 0, 2, 1, 1)
        self.pushButton_Phai = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Phai.setObjectName("pushButton_Phai")
        self.gridLayout.addWidget(self.pushButton_Phai, 1, 2, 1, 1)
        self.pushButton_Lui = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Lui.setObjectName("pushButton_Lui")
        self.gridLayout.addWidget(self.pushButton_Lui, 2, 1, 1, 1)
        self.pushButton_Trai = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Trai.setObjectName("pushButton_Trai")
        self.gridLayout.addWidget(self.pushButton_Trai, 1, 0, 1, 1)
        self.pushButton_Dung = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Dung.setObjectName("pushButton_Dung")
        self.gridLayout.addWidget(self.pushButton_Dung, 1, 1, 1, 1)
        self.pushButton_Cham = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Cham.setObjectName("pushButton_Cham")
        self.gridLayout.addWidget(self.pushButton_Cham, 2, 2, 1, 1)
        self.pushButton_Tien = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Tien.setObjectName("pushButton_Tien")
        self.gridLayout.addWidget(self.pushButton_Tien, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 90, 264, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_GhiAm = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_GhiAm.setObjectName("pushButton_GhiAm")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.pushButton_GhiAm)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.textEdit)
        self.pushButton_Gui = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Gui.setObjectName("pushButton_Gui")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.pushButton_Gui)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 896, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_GhiAm.clicked.connect(MainWindow.slot_PredictMic) # type: ignore
        self.pushButton_Gui.clicked.connect(MainWindow.slot_Publish) # type: ignore
        self.pushButton_Nhanh.clicked.connect(MainWindow.slot_Command) # type: ignore
        self.pushButton_Tien.clicked.connect(MainWindow.slot_Command) # type: ignore
        self.pushButton_Trai.clicked.connect(MainWindow.slot_Command) # type: ignore
        self.pushButton_Dung.clicked.connect(MainWindow.slot_Command) # type: ignore
        self.pushButton_Phai.clicked.connect(MainWindow.slot_Command) # type: ignore
        self.pushButton_Cham.clicked.connect(MainWindow.slot_Command) # type: ignore
        self.pushButton_Lui.clicked.connect(MainWindow.slot_Command) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Nhanh.setText(_translate("MainWindow", "Nhanh"))
        self.pushButton_Phai.setText(_translate("MainWindow", "Phải"))
        self.pushButton_Lui.setText(_translate("MainWindow", "Lùi"))
        self.pushButton_Trai.setText(_translate("MainWindow", "Trái"))
        self.pushButton_Dung.setText(_translate("MainWindow", "Dừng"))
        self.pushButton_Cham.setText(_translate("MainWindow", "Chậm"))
        self.pushButton_Tien.setText(_translate("MainWindow", "Tiến"))
        self.pushButton_GhiAm.setText(_translate("MainWindow", "Ghi âm"))
        self.label.setText(_translate("MainWindow", "                        Lệnh đã nhận"))
        self.pushButton_Gui.setText(_translate("MainWindow", "Gửi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
